using Avalonia;
using Avalonia.Media;
using Cbdb.App.Core;

namespace Cbdb.App.Avalonia.Localization;

public sealed class AppLocalizationService : ILocalizationService {
    private readonly Dictionary<UiLanguage, Dictionary<string, string>> _resources = new() {
        [UiLanguage.English] = new(StringComparer.OrdinalIgnoreCase) {
            ["window.title"] = "NAVIGATION_PANE",
            ["header.main"] = "China Biographical Database (CBDB)",
            ["button.report_error"] = "Report an Error",
            ["button.change_index_address"] = "Change Index Address Ranking",
            ["button.relink_tables"] = "Relink Tables / Change Dataset",
            ["button.users_guide"] = "Users Guide",
            ["button.exit"] = "Exit",
            ["module.browser"] = "Look Up Data on an Individual",
            ["module.entry"] = "Query by Methods of Entry into Government",
            ["module.office"] = "Query Office Holding",
            ["module.kinship"] = "Query Kinship",
            ["module.associations"] = "Query Associations",
            ["module.networks"] = "Query Social Networks",
            ["module.association_pairs"] = "Query Pair-wise Associations",
            ["module.place"] = "Query Place Associations",
            ["module.status"] = "Query Status",
            ["module.texts"] = "Query Texts",
            ["status.ready"] = "Ready",
            ["status.checking"] = "Checking...",
            ["status.connected"] = "Connected",
            ["status.failed"] = "Failed",
            ["status.language_set"] = "Language switched",
            ["status.module_selected"] = "Module selected: {0}",
            ["msg.index_addr_todo"] = "This module remains to be ported after the navigation shell.",
            ["msg.user_guide_opened"] = "Users Guide opened",
            ["msg.user_guide_failed"] = "Users Guide failed",
            ["msg.user_guide_not_found"] = "Guide file not found: {0}",
            ["msg.sqlite_missing"] = "SQLite file does not exist. Please choose a valid CBDB SQLite file first.",
            ["msg.module_todo"] = "{0} has not been ported to Avalonia yet.",
            ["msg.browser_todo"] = "Person Browser shell is the next Avalonia port target.",
            ["msg.report_opened"] = "Opened error report page",
            ["dialog.select_sqlite"] = "Select CBDB SQLite file",
            ["browser.window_title"] = "Person Browser",
            ["browser.search"] = "Search",
            ["browser.clear"] = "Clear",
            ["browser.save_to_file"] = "Save to File",
            ["browser.keyword_tooltip"] = "Search by name, Chinese name, pinyin, or alt names",
            ["browser.grid_person_id"] = "ID",
            ["browser.grid_name_chn"] = "Chinese Name",
            ["browser.grid_name_rm"] = "Pinyin",
            ["browser.grid_index_year"] = "Index Year",
            ["browser.grid_index_address"] = "Index Address",
            ["browser.person_id"] = "Person ID",
            ["browser.name_chn"] = "Chinese Name",
            ["browser.name"] = "Name",
            ["browser.gender"] = "Gender",
            ["browser.birth_year"] = "Birth Year",
            ["browser.death_year"] = "Death Year",
            ["browser.dynasty"] = "Dynasty",
            ["browser.index_year"] = "Index Year",
            ["browser.index_year_type"] = "Index Year Type",
            ["browser.index_year_source"] = "Index Year Source",
            ["browser.index_address"] = "Index Address",
            ["browser.index_address_type"] = "Index Address Type",
            ["browser.tab_basic"] = "Basic Information",
            ["browser.tab_addresses"] = "Addresses",
            ["browser.tab_alt_names"] = "Alt. Names",
            ["browser.tab_writings"] = "Writings",
            ["browser.tab_postings"] = "Postings",
            ["browser.tab_entry"] = "Entry",
            ["browser.tab_events"] = "Events",
            ["browser.tab_status"] = "Status",
            ["browser.tab_kinship"] = "Kinship",
            ["browser.tab_associations"] = "Associations",
            ["browser.tab_possessions"] = "Possessions",
            ["browser.tab_sources"] = "Sources",
            ["browser.tab_institutions"] = "Institutions",
            ["browser.addresses_none"] = "The selected person has no address records.",
            ["browser.address_sequence"] = "Sequence",
            ["browser.address_maternal"] = "Maternal",
            ["browser.address_type"] = "Address Type",
            ["browser.address_name"] = "Address",
            ["browser.address_first"] = "First Year",
            ["browser.address_last"] = "Last Year",
            ["browser.address_source"] = "Source",
            ["browser.address_pages"] = "Pages",
            ["browser.address_notes"] = "Notes",
            ["browser.address_intercalary"] = "Intercalary",
            ["browser.alt_names_none"] = "The selected person has no alternate-name records.",
            ["browser.alt_name_chn"] = "Alt. Name (Chinese)",
            ["browser.alt_name"] = "Alt. Name",
            ["browser.alt_name_type"] = "Name Type",
            ["browser.writings_none"] = "The selected person has no writing records.",
            ["browser.writing_title"] = "Title",
            ["browser.writing_title_chn"] = "Title (Chinese)",
            ["browser.writing_role"] = "Role",
            ["browser.writing_year"] = "Year",
            ["browser.writing_nianhao"] = "Nianhao",
            ["browser.writing_range"] = "Range",
            ["browser.entry_none"] = "The selected person has no entry records.",
            ["browser.entry_method"] = "Entry Method",
            ["browser.entry_year"] = "Year",
            ["browser.entry_nianhao"] = "Nianhao",
            ["browser.entry_exam_rank"] = "Exam Rank",
            ["browser.entry_age"] = "Age",
            ["browser.entry_dynasty"] = "Dynasty",
            ["browser.entry_parental_status"] = "Parental Status",
            ["browser.entry_kinship"] = "Kinship",
            ["browser.entry_kin_person"] = "Kin Person",
            ["browser.entry_association"] = "Association",
            ["browser.entry_associate_person"] = "Associated Person",
            ["browser.entry_institution"] = "Institution",
            ["browser.entry_address"] = "Entry Address",
            ["browser.entry_posting_notes"] = "Posting Notes",
            ["browser.status_none"] = "The selected person has no status records.",
            ["browser.status_name"] = "Status",
            ["browser.possessions_none"] = "The selected person has no possession records.",
            ["browser.possession_name"] = "Possession",
            ["browser.possession_action"] = "Action",
            ["browser.possession_quantity"] = "Quantity",
            ["browser.possession_date"] = "Date",
            ["browser.possession_address"] = "Address",
            ["browser.sources_none"] = "The selected person has no source records.",
            ["browser.source_title"] = "Source",
            ["browser.source_title_chn"] = "Source (Chinese)",
            ["browser.source_main"] = "Main Source",
            ["browser.source_self_bio"] = "Self Biography",
            ["browser.source_hyperlink"] = "Hyperlink",
            ["browser.institutions_none"] = "The selected person has no institution records.",
            ["browser.institution_name"] = "Institution",
            ["browser.institution_name_chn"] = "Institution (Chinese)",
            ["browser.institution_role"] = "Role",
            ["browser.institution_begin"] = "Begin",
            ["browser.institution_end"] = "End",
            ["browser.institution_place"] = "Place",
            ["browser.institution_place_type"] = "Place Type",
            ["browser.institution_coords"] = "Coordinates",
            ["browser.all_fields_header"] = "All BIOG_MAIN Fields",
            ["browser.search_result_count"] = "Results: {0}",
            ["browser.tab_placeholder"] = "Tab content will be ported later.",
            ["browser.no_selection"] = "Select a person to view details.",
            ["browser.male"] = "Male",
            ["browser.female"] = "Female",
            ["browser.unknown"] = "Unknown",
            ["browser.no_data_to_export"] = "There is no data to export."
        },
        [UiLanguage.TraditionalChinese] = new(StringComparer.OrdinalIgnoreCase) {
            ["window.title"] = "導航面板",
            ["header.main"] = "中國歷代人物傳記資料庫",
            ["button.report_error"] = "問題回報",
            ["button.change_index_address"] = "修改索引地址排序",
            ["button.relink_tables"] = "切換資料集",
            ["button.users_guide"] = "用戶指南",
            ["button.exit"] = "退出",
            ["module.browser"] = "按人查詢",
            ["module.entry"] = "按入仕途徑查詢",
            ["module.office"] = "官職查詢",
            ["module.kinship"] = "親屬關係查詢",
            ["module.associations"] = "社會關係查詢",
            ["module.networks"] = "社會網絡查詢",
            ["module.association_pairs"] = "兩人關係網交集查詢",
            ["module.place"] = "地區關係查詢",
            ["module.status"] = "社會區分查詢",
            ["module.texts"] = "文本關係查詢",
            ["status.ready"] = "就緒",
            ["status.checking"] = "檢查中...",
            ["status.connected"] = "連線成功",
            ["status.failed"] = "連線失敗",
            ["status.language_set"] = "語言已切換",
            ["status.module_selected"] = "已選模組：{0}",
            ["msg.index_addr_todo"] = "導航殼完成後再移植此模組。",
            ["msg.user_guide_opened"] = "已開啟用戶指南",
            ["msg.user_guide_failed"] = "開啟用戶指南失敗",
            ["msg.user_guide_not_found"] = "找不到指南檔案：{0}",
            ["msg.sqlite_missing"] = "SQLite 檔案不存在，請先選擇有效的 CBDB SQLite 檔案。",
            ["msg.module_todo"] = "模組「{0}」尚未移植到 Avalonia。",
            ["msg.browser_todo"] = "人物瀏覽視窗是下一個 Avalonia 移植目標。",
            ["msg.report_opened"] = "已開啟問題回報頁面",
            ["dialog.select_sqlite"] = "選擇 CBDB SQLite 檔案",
            ["browser.window_title"] = "人物瀏覽",
            ["browser.search"] = "查詢",
            ["browser.clear"] = "清除",
            ["browser.save_to_file"] = "存成檔案",
            ["browser.keyword_tooltip"] = "可用姓名、中文名、拼音或別名查詢",
            ["browser.grid_person_id"] = "人物 ID",
            ["browser.grid_name_chn"] = "中文姓名",
            ["browser.grid_name_rm"] = "拼音",
            ["browser.grid_index_year"] = "索引年",
            ["browser.grid_index_address"] = "索引地址",
            ["browser.person_id"] = "人物 ID",
            ["browser.name_chn"] = "中文姓名",
            ["browser.name"] = "姓名",
            ["browser.gender"] = "性別",
            ["browser.birth_year"] = "出生年",
            ["browser.death_year"] = "卒年",
            ["browser.dynasty"] = "朝代",
            ["browser.index_year"] = "索引年",
            ["browser.index_year_type"] = "索引年類型",
            ["browser.index_year_source"] = "索引年來源",
            ["browser.index_address"] = "索引地址",
            ["browser.index_address_type"] = "索引地址類型",
            ["browser.tab_basic"] = "基本資料",
            ["browser.tab_addresses"] = "地址",
            ["browser.tab_alt_names"] = "別名",
            ["browser.tab_writings"] = "著作",
            ["browser.tab_postings"] = "任官",
            ["browser.tab_entry"] = "入仕",
            ["browser.tab_events"] = "事件",
            ["browser.tab_status"] = "身份",
            ["browser.tab_kinship"] = "親屬",
            ["browser.tab_associations"] = "社會關係",
            ["browser.tab_possessions"] = "財產",
            ["browser.tab_sources"] = "來源",
            ["browser.tab_institutions"] = "機構",
            ["browser.addresses_none"] = "所選人物無地址記錄。",
            ["browser.address_sequence"] = "序號",
            ["browser.address_maternal"] = "母系",
            ["browser.address_type"] = "地址類型",
            ["browser.address_name"] = "地址",
            ["browser.address_first"] = "起始年份",
            ["browser.address_last"] = "結束年份",
            ["browser.address_source"] = "來源",
            ["browser.address_pages"] = "頁碼",
            ["browser.address_notes"] = "注釋",
            ["browser.address_intercalary"] = "閏月",
            ["browser.alt_names_none"] = "所選人物無別名記錄。",
            ["browser.alt_name_chn"] = "別名（中文）",
            ["browser.alt_name"] = "別名",
            ["browser.alt_name_type"] = "名稱類型",
            ["browser.writings_none"] = "所選人物無著作記錄。",
            ["browser.writing_title"] = "書名",
            ["browser.writing_title_chn"] = "書名（中文）",
            ["browser.writing_role"] = "角色",
            ["browser.writing_year"] = "年份",
            ["browser.writing_nianhao"] = "年號",
            ["browser.writing_range"] = "時限",
            ["browser.entry_none"] = "所選人物無入仕記錄。",
            ["browser.entry_method"] = "入仕方式",
            ["browser.entry_year"] = "年份",
            ["browser.entry_nianhao"] = "年號",
            ["browser.entry_exam_rank"] = "考試名次",
            ["browser.entry_age"] = "年齡",
            ["browser.entry_dynasty"] = "朝代",
            ["browser.entry_parental_status"] = "父祖狀態",
            ["browser.entry_kinship"] = "親屬關係",
            ["browser.entry_kin_person"] = "相關親屬",
            ["browser.entry_association"] = "關係類型",
            ["browser.entry_associate_person"] = "相關人物",
            ["browser.entry_institution"] = "機構",
            ["browser.entry_address"] = "入仕地點",
            ["browser.entry_posting_notes"] = "任官注記",
            ["browser.status_none"] = "所選人物無身份記錄。",
            ["browser.status_name"] = "身份",
            ["browser.possessions_none"] = "所選人物無財產記錄。",
            ["browser.possession_name"] = "財產",
            ["browser.possession_action"] = "動作",
            ["browser.possession_quantity"] = "數量",
            ["browser.possession_date"] = "日期",
            ["browser.possession_address"] = "地點",
            ["browser.sources_none"] = "所選人物無來源記錄。",
            ["browser.source_title"] = "來源",
            ["browser.source_title_chn"] = "來源（中文）",
            ["browser.source_main"] = "主要來源",
            ["browser.source_self_bio"] = "自傳",
            ["browser.source_hyperlink"] = "連結",
            ["browser.institutions_none"] = "所選人物無機構記錄。",
            ["browser.institution_name"] = "機構",
            ["browser.institution_name_chn"] = "機構（中文）",
            ["browser.institution_role"] = "角色",
            ["browser.institution_begin"] = "起始",
            ["browser.institution_end"] = "結束",
            ["browser.institution_place"] = "地點",
            ["browser.institution_place_type"] = "地點類型",
            ["browser.institution_coords"] = "座標",
            ["browser.all_fields_header"] = "BIOG_MAIN 全部欄位",
            ["browser.search_result_count"] = "結果數：{0}",
            ["browser.tab_placeholder"] = "此選項卡內容後續再移植。",
            ["browser.no_selection"] = "請先選擇人物以查看詳細資料。",
            ["browser.male"] = "男",
            ["browser.female"] = "女",
            ["browser.unknown"] = "未詳",
            ["browser.no_data_to_export"] = "目前沒有可匯出的資料。"
        },
        [UiLanguage.SimplifiedChinese] = new(StringComparer.OrdinalIgnoreCase) {
            ["window.title"] = "导航面板",
            ["header.main"] = "中国历代人物传记资料库",
            ["button.report_error"] = "问题回报",
            ["button.change_index_address"] = "修改索引地址排序",
            ["button.relink_tables"] = "切换数据集",
            ["button.users_guide"] = "用户指南",
            ["button.exit"] = "退出",
            ["module.browser"] = "按人查询",
            ["module.entry"] = "按入仕途径查询",
            ["module.office"] = "官职查询",
            ["module.kinship"] = "亲属关系查询",
            ["module.associations"] = "社会关系查询",
            ["module.networks"] = "社会网络查询",
            ["module.association_pairs"] = "两人关系网交集查询",
            ["module.place"] = "地区关系查询",
            ["module.status"] = "社会区分查询",
            ["module.texts"] = "文本关系查询",
            ["status.ready"] = "就绪",
            ["status.checking"] = "检查中...",
            ["status.connected"] = "连接成功",
            ["status.failed"] = "连接失败",
            ["status.language_set"] = "语言已切换",
            ["status.module_selected"] = "已选模块：{0}",
            ["msg.index_addr_todo"] = "导航壳完成后再移植此模块。",
            ["msg.user_guide_opened"] = "已打开用户指南",
            ["msg.user_guide_failed"] = "打开用户指南失败",
            ["msg.user_guide_not_found"] = "找不到指南文件：{0}",
            ["msg.sqlite_missing"] = "SQLite 文件不存在，请先选择有效的 CBDB SQLite 文件。",
            ["msg.module_todo"] = "模块“{0}”尚未移植到 Avalonia。",
            ["msg.browser_todo"] = "人物浏览窗口是下一个 Avalonia 移植目标。",
            ["msg.report_opened"] = "已打开问题回报页面",
            ["dialog.select_sqlite"] = "选择 CBDB SQLite 文件",
            ["browser.window_title"] = "人物浏览",
            ["browser.search"] = "查询",
            ["browser.clear"] = "清除",
            ["browser.save_to_file"] = "存成文件",
            ["browser.keyword_tooltip"] = "可用姓名、中文名、拼音或别名查询",
            ["browser.grid_person_id"] = "人物 ID",
            ["browser.grid_name_chn"] = "中文姓名",
            ["browser.grid_name_rm"] = "拼音",
            ["browser.grid_index_year"] = "索引年",
            ["browser.grid_index_address"] = "索引地址",
            ["browser.person_id"] = "人物 ID",
            ["browser.name_chn"] = "中文姓名",
            ["browser.name"] = "姓名",
            ["browser.gender"] = "性别",
            ["browser.birth_year"] = "出生年",
            ["browser.death_year"] = "卒年",
            ["browser.dynasty"] = "朝代",
            ["browser.index_year"] = "索引年",
            ["browser.index_year_type"] = "索引年类型",
            ["browser.index_year_source"] = "索引年来源",
            ["browser.index_address"] = "索引地址",
            ["browser.index_address_type"] = "索引地址类型",
            ["browser.tab_basic"] = "基本资料",
            ["browser.tab_addresses"] = "地址",
            ["browser.tab_alt_names"] = "别名",
            ["browser.tab_writings"] = "著作",
            ["browser.tab_postings"] = "任官",
            ["browser.tab_entry"] = "入仕",
            ["browser.tab_events"] = "事件",
            ["browser.tab_status"] = "身份",
            ["browser.tab_kinship"] = "亲属",
            ["browser.tab_associations"] = "社会关系",
            ["browser.tab_possessions"] = "财产",
            ["browser.tab_sources"] = "来源",
            ["browser.tab_institutions"] = "机构",
            ["browser.addresses_none"] = "所选人物无地址记录。",
            ["browser.address_sequence"] = "序号",
            ["browser.address_maternal"] = "母系",
            ["browser.address_type"] = "地址类型",
            ["browser.address_name"] = "地址",
            ["browser.address_first"] = "起始年份",
            ["browser.address_last"] = "结束年份",
            ["browser.address_source"] = "来源",
            ["browser.address_pages"] = "页码",
            ["browser.address_notes"] = "注释",
            ["browser.address_intercalary"] = "闰月",
            ["browser.alt_names_none"] = "所选人物无别名记录。",
            ["browser.alt_name_chn"] = "别名（中文）",
            ["browser.alt_name"] = "别名",
            ["browser.alt_name_type"] = "名称类型",
            ["browser.writings_none"] = "所选人物无著作记录。",
            ["browser.writing_title"] = "书名",
            ["browser.writing_title_chn"] = "书名（中文）",
            ["browser.writing_role"] = "角色",
            ["browser.writing_year"] = "年份",
            ["browser.writing_nianhao"] = "年号",
            ["browser.writing_range"] = "时限",
            ["browser.entry_none"] = "所选人物无入仕记录。",
            ["browser.entry_method"] = "入仕方式",
            ["browser.entry_year"] = "年份",
            ["browser.entry_nianhao"] = "年号",
            ["browser.entry_exam_rank"] = "考试名次",
            ["browser.entry_age"] = "年龄",
            ["browser.entry_dynasty"] = "朝代",
            ["browser.entry_parental_status"] = "父祖状态",
            ["browser.entry_kinship"] = "亲属关系",
            ["browser.entry_kin_person"] = "相关亲属",
            ["browser.entry_association"] = "关系类型",
            ["browser.entry_associate_person"] = "相关人物",
            ["browser.entry_institution"] = "机构",
            ["browser.entry_address"] = "入仕地点",
            ["browser.entry_posting_notes"] = "任官注记",
            ["browser.status_none"] = "所选人物无身份记录。",
            ["browser.status_name"] = "身份",
            ["browser.possessions_none"] = "所选人物无财产记录。",
            ["browser.possession_name"] = "财产",
            ["browser.possession_action"] = "动作",
            ["browser.possession_quantity"] = "数量",
            ["browser.possession_date"] = "日期",
            ["browser.possession_address"] = "地点",
            ["browser.sources_none"] = "所选人物无来源记录。",
            ["browser.source_title"] = "来源",
            ["browser.source_title_chn"] = "来源（中文）",
            ["browser.source_main"] = "主要来源",
            ["browser.source_self_bio"] = "自传",
            ["browser.source_hyperlink"] = "链接",
            ["browser.institutions_none"] = "所选人物无机构记录。",
            ["browser.institution_name"] = "机构",
            ["browser.institution_name_chn"] = "机构（中文）",
            ["browser.institution_role"] = "角色",
            ["browser.institution_begin"] = "起始",
            ["browser.institution_end"] = "结束",
            ["browser.institution_place"] = "地点",
            ["browser.institution_place_type"] = "地点类型",
            ["browser.institution_coords"] = "坐标",
            ["browser.all_fields_header"] = "BIOG_MAIN 全部字段",
            ["browser.search_result_count"] = "结果数：{0}",
            ["browser.tab_placeholder"] = "此选项卡内容后续再移植。",
            ["browser.no_selection"] = "请先选择人物以查看详细资料。",
            ["browser.male"] = "男",
            ["browser.female"] = "女",
            ["browser.unknown"] = "未详",
            ["browser.no_data_to_export"] = "目前没有可导出的数据。"
        }
    };

    public UiLanguage CurrentLanguage { get; private set; } = UiLanguage.TraditionalChinese;

    public event EventHandler? LanguageChanged;

    public void SetLanguage(UiLanguage language) {
        if (CurrentLanguage == language) {
            return;
        }

        CurrentLanguage = language;
        ApplyFontFamily(language);
        LanguageChanged?.Invoke(this, EventArgs.Empty);
    }

    public string Get(string key) {
        if (_resources.TryGetValue(CurrentLanguage, out var dict) && dict.TryGetValue(key, out var value)) {
            return value;
        }

        if (_resources[UiLanguage.English].TryGetValue(key, out var fallback)) {
            return fallback;
        }

        return key;
    }

    public void ApplyCurrentLanguage() {
        ApplyFontFamily(CurrentLanguage);
    }

    private static void ApplyFontFamily(UiLanguage language) {
        if (Application.Current is null) {
            return;
        }

        var familyName = language switch {
            UiLanguage.SimplifiedChinese => "PingFang SC, Microsoft YaHei UI, sans-serif",
            UiLanguage.TraditionalChinese => "PingFang TC, Microsoft JhengHei UI, sans-serif",
            _ => "SF Pro Text, Segoe UI, sans-serif"
        };

        Application.Current.Resources["AppFontFamily"] = new FontFamily(familyName);
    }
}
