namespace Cbdb.App.Core;

public sealed record OfficeQueryRecord(
    int PersonId,
    string? NameChn,
    string? Name,
    int? IndexYear,
    string? IndexYearType,
    string? Sex,
    string? Dynasty,
    int? IndexAddressId,
    string? IndexAddress,
    string? IndexAddressType,
    int PostingId,
    int Sequence,
    string OfficeCode,
    string? Office,
    string? AppointmentType,
    string? AssumeOffice,
    string? Category,
    int? FirstYear,
    string? FirstNianhao,
    int? FirstNianhaoYear,
    string? FirstRange,
    int? LastYear,
    string? LastNianhao,
    int? LastNianhaoYear,
    string? LastRange,
    string? Institution,
    int? OfficeAddressId,
    string? OfficeAddress,
    double? OfficeXCoord,
    double? OfficeYCoord,
    int OfficeXyCount,
    string? Source,
    string? Pages,
    string? Notes
);
