namespace Cbdb.App.Core;

public sealed record PersonDetail(
    int PersonId,
    string? SurnameChn,
    string? MingziChn,
    string? Surname,
    string? Mingzi,
    string? SurnameProper,
    string? MingziProper,
    string? SurnameRm,
    string? MingziRm,
    string? Name,
    string? NameChn,
    int? IndexYear,
    string? Dynasty,
    string? DynastyChn,
    int? BirthYear,
    int? DeathYear,
    string? Gender,
    string? IndexAddress,
    string? IndexAddressChn,
    int AddressCount,
    int AltNameCount,
    int KinCount,
    int AssocCount,
    int OfficeCount,
    int EntryCount,
    int EventCount,
    int StatusCount,
    int TextCount,
    int PossessionCount,
    int SourceCount,
    int InstitutionCount,
    IReadOnlyList<PersonFieldValue> Fields
);
