namespace Cbdb.App.Core;

public sealed record StatusQueryRecord(
    int PersonId,
    string? NameChn,
    string? Name,
    int? IndexYear,
    string? IndexYearType,
    string? Sex,
    string? Dynasty,
    int? IndexAddressId,
    string? IndexAddress,
    double? XCoord,
    double? YCoord,
    int Sequence,
    string? Status,
    string StatusCode,
    int? FirstYear,
    string? FirstNianhao,
    int? FirstNianhaoYear,
    string? FirstRange,
    int? LastYear,
    string? LastNianhao,
    int? LastNianhaoYear,
    string? LastRange,
    string? Supplement,
    string? Source,
    string? Pages,
    string? Notes
);
