using Cbdb.App.Core;

namespace Cbdb.App.Desktop.Localization;

public sealed class AppLocalizationService : ILocalizationService {
    private readonly Dictionary<UiLanguage, Dictionary<string, string>> _resources = new() {
        [UiLanguage.English] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase) {
            ["window.title"] = "NAVIGATION_PANE",
            ["header.main"] = "China Biographical Database (CBDB)",
            ["button.browse"] = "Browse",
            ["button.check_db"] = "Check DB",
            ["button.users_guide"] = "Users Guide",
            ["button.exit"] = "Exit",
            ["button.report_error"] = "Report an Error",
            ["button.change_index_address"] = "Change Index Address Ranking",
            ["button.relink_tables"] = "Relink Tables / Change Dataset",
            ["module.browser"] = "Look Up Data on an Individual",
            ["module.entry"] = "Query by Methods of Entry into Government",
            ["module.office"] = "Query Office Holding",
            ["module.kinship"] = "Query Kinship",
            ["module.associations"] = "Query Associations",
            ["module.networks"] = "Query Social Networks",
            ["module.association_pairs"] = "Query Pair-wise Associations",
            ["module.place"] = "Query Place Associations",
            ["module.status"] = "Query Status",
            ["module.texts"] = "Query Texts",
            ["status.ready"] = "Ready",
            ["status.checking"] = "Checking...",
            ["status.connected"] = "Connected",
            ["status.failed"] = "Failed",
            ["status.language_set"] = "Language switched",
            ["status.module_selected"] = "Module selected: {0}",
            ["msg.module_todo"] = "{0} module is not implemented yet. Next step: wire this button to its page/query workflow.",
            ["msg.report_todo"] = "Error reporting flow not wired yet. We can route this to an issue form or local feedback dialog.",
            ["msg.index_addr_todo"] = "This will open Address Rank editor + Index Address rebuild page in the next implementation step.",
            ["msg.dataset_hint"] = "Use Browse to select another SQLite file, then click Check DB.",
            ["msg.user_guide_opened"] = "Users Guide opened",
            ["msg.user_guide_failed"] = "Users Guide failed",
            ["msg.user_guide_not_found"] = "Guide file not found: {0}",
            ["msg.sqlite_missing"] = "SQLite file does not exist. Please choose a valid CBDB SQLite file first.",
            ["msg.browser_opened"] = "Person Browser opened.",
            ["dialog.select_sqlite"] = "Select CBDB SQLite file",
            ["browser.window_title"] = "Person Browser",
            ["browser.search"] = "Search",
            ["browser.clear"] = "Clear",
            ["browser.keyword_tooltip"] = "Search by name, Chinese name, or alt names",
            ["browser.tab_basic"] = "Basic",
            ["browser.tab_counts"] = "Counts",
            ["browser.grid_person_id"] = "ID",
            ["browser.grid_name"] = "Name",
            ["browser.grid_name_chn"] = "Chinese Name",
            ["browser.grid_index_year"] = "Index Year",
            ["browser.person_id"] = "Person ID",
            ["browser.name"] = "Name",
            ["browser.name_chn"] = "Chinese Name",
            ["browser.dynasty"] = "Dynasty",
            ["browser.index_year"] = "Index Year",
            ["browser.birth_death"] = "Birth / Death",
            ["browser.gender"] = "Gender",
            ["browser.index_address"] = "Index Address",
            ["browser.count_altnames"] = "Alt Names",
            ["browser.count_kin"] = "Kinship",
            ["browser.count_assoc"] = "Associations",
            ["browser.count_office"] = "Offices",
            ["browser.count_entry"] = "Entries",
            ["browser.count_status"] = "Status",
            ["browser.count_texts"] = "Texts",
            ["browser.search_result_count"] = "Results: {0}",
            ["browser.sqlite_missing"] = "SQLite file does not exist."
        },
        [UiLanguage.TraditionalChinese] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase) {
            ["window.title"] = "導航面板",
            ["header.main"] = "中國歷代人物傳記資料庫",
            ["button.browse"] = "選擇檔案",
            ["button.check_db"] = "檢查資料庫",
            ["button.users_guide"] = "用戶指南",
            ["button.exit"] = "退出",
            ["button.report_error"] = "問題回報",
            ["button.change_index_address"] = "修改索引地址排序",
            ["button.relink_tables"] = "切換資料集",
            ["module.browser"] = "按人查詢",
            ["module.entry"] = "按入仕途徑查詢",
            ["module.office"] = "官職查詢",
            ["module.kinship"] = "親屬關係查詢",
            ["module.associations"] = "社會關係查詢",
            ["module.networks"] = "社會網絡查詢",
            ["module.association_pairs"] = "兩人關係網交集查詢",
            ["module.place"] = "地區關係查詢",
            ["module.status"] = "社會區分查詢",
            ["module.texts"] = "文本關係查詢",
            ["status.ready"] = "就緒",
            ["status.checking"] = "檢查中...",
            ["status.connected"] = "連線成功",
            ["status.failed"] = "連線失敗",
            ["status.language_set"] = "語言已切換",
            ["status.module_selected"] = "已選模組：{0}",
            ["msg.module_todo"] = "模組「{0}」尚未實作。下一步將接入對應查詢頁面。",
            ["msg.report_todo"] = "問題回報流程尚未接線，後續可接入線上表單或本地回饋視窗。",
            ["msg.index_addr_todo"] = "下一步會在此接入 Address Rank 編輯與 Index Address 重建功能。",
            ["msg.dataset_hint"] = "請先選擇 SQLite 檔案，再按「檢查資料庫」。",
            ["msg.user_guide_opened"] = "已開啟用戶指南",
            ["msg.user_guide_failed"] = "開啟用戶指南失敗",
            ["msg.user_guide_not_found"] = "找不到指南檔案：{0}",
            ["msg.sqlite_missing"] = "SQLite 檔案不存在，請先選擇有效的 CBDB SQLite 檔案。",
            ["msg.browser_opened"] = "已開啟人物瀏覽。",
            ["dialog.select_sqlite"] = "選擇 CBDB SQLite 檔案",
            ["browser.window_title"] = "人物瀏覽",
            ["browser.search"] = "查詢",
            ["browser.clear"] = "清除",
            ["browser.keyword_tooltip"] = "可用姓名、中文名或別名查詢",
            ["browser.tab_basic"] = "基本",
            ["browser.tab_counts"] = "統計",
            ["browser.grid_person_id"] = "ID",
            ["browser.grid_name"] = "姓名",
            ["browser.grid_name_chn"] = "中文名",
            ["browser.grid_index_year"] = "索引年",
            ["browser.person_id"] = "人物 ID",
            ["browser.name"] = "姓名",
            ["browser.name_chn"] = "中文名",
            ["browser.dynasty"] = "朝代",
            ["browser.index_year"] = "索引年",
            ["browser.birth_death"] = "生 / 卒",
            ["browser.gender"] = "性別",
            ["browser.index_address"] = "索引地址",
            ["browser.count_altnames"] = "別名",
            ["browser.count_kin"] = "親屬",
            ["browser.count_assoc"] = "關係",
            ["browser.count_office"] = "任官",
            ["browser.count_entry"] = "入仕",
            ["browser.count_status"] = "身份",
            ["browser.count_texts"] = "文本",
            ["browser.search_result_count"] = "結果數：{0}",
            ["browser.sqlite_missing"] = "SQLite 檔案不存在。"
        },
        [UiLanguage.SimplifiedChinese] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase) {
            ["window.title"] = "导航面板",
            ["header.main"] = "中国历代人物传记资料库",
            ["button.browse"] = "选择文件",
            ["button.check_db"] = "检查数据库",
            ["button.users_guide"] = "用户指南",
            ["button.exit"] = "退出",
            ["button.report_error"] = "问题回报",
            ["button.change_index_address"] = "修改索引地址排序",
            ["button.relink_tables"] = "切换数据集",
            ["module.browser"] = "按人查询",
            ["module.entry"] = "按入仕途径查询",
            ["module.office"] = "官职查询",
            ["module.kinship"] = "亲属关系查询",
            ["module.associations"] = "社会关系查询",
            ["module.networks"] = "社会网络查询",
            ["module.association_pairs"] = "两人关系网交集查询",
            ["module.place"] = "地区关系查询",
            ["module.status"] = "社会区分查询",
            ["module.texts"] = "文本关系查询",
            ["status.ready"] = "就绪",
            ["status.checking"] = "检查中...",
            ["status.connected"] = "连接成功",
            ["status.failed"] = "连接失败",
            ["status.language_set"] = "语言已切换",
            ["status.module_selected"] = "已选模块：{0}",
            ["msg.module_todo"] = "模块“{0}”尚未实现。下一步将接入对应查询页面。",
            ["msg.report_todo"] = "问题回报流程尚未接线，后续可接入线上表单或本地反馈窗口。",
            ["msg.index_addr_todo"] = "下一步会在此接入 Address Rank 编辑与 Index Address 重建功能。",
            ["msg.dataset_hint"] = "请先选择 SQLite 文件，再点“检查数据库”。",
            ["msg.user_guide_opened"] = "已打开用户指南",
            ["msg.user_guide_failed"] = "打开用户指南失败",
            ["msg.user_guide_not_found"] = "找不到指南文件：{0}",
            ["msg.sqlite_missing"] = "SQLite 文件不存在，请先选择有效的 CBDB SQLite 文件。",
            ["msg.browser_opened"] = "已打开人物浏览。",
            ["dialog.select_sqlite"] = "选择 CBDB SQLite 文件",
            ["browser.window_title"] = "人物浏览",
            ["browser.search"] = "查询",
            ["browser.clear"] = "清除",
            ["browser.keyword_tooltip"] = "可用姓名、中文名或别名查询",
            ["browser.tab_basic"] = "基本",
            ["browser.tab_counts"] = "统计",
            ["browser.grid_person_id"] = "ID",
            ["browser.grid_name"] = "姓名",
            ["browser.grid_name_chn"] = "中文名",
            ["browser.grid_index_year"] = "索引年",
            ["browser.person_id"] = "人物 ID",
            ["browser.name"] = "姓名",
            ["browser.name_chn"] = "中文名",
            ["browser.dynasty"] = "朝代",
            ["browser.index_year"] = "索引年",
            ["browser.birth_death"] = "生 / 卒",
            ["browser.gender"] = "性别",
            ["browser.index_address"] = "索引地址",
            ["browser.count_altnames"] = "别名",
            ["browser.count_kin"] = "亲属",
            ["browser.count_assoc"] = "关系",
            ["browser.count_office"] = "任官",
            ["browser.count_entry"] = "入仕",
            ["browser.count_status"] = "身份",
            ["browser.count_texts"] = "文本",
            ["browser.search_result_count"] = "结果数：{0}",
            ["browser.sqlite_missing"] = "SQLite 文件不存在。"
        }
    };

    public UiLanguage CurrentLanguage { get; private set; } = UiLanguage.TraditionalChinese;

    public event EventHandler? LanguageChanged;

    public void SetLanguage(UiLanguage language) {
        if (CurrentLanguage == language) {
            return;
        }

        CurrentLanguage = language;
        LanguageChanged?.Invoke(this, EventArgs.Empty);
    }

    public string Get(string key) {
        if (_resources.TryGetValue(CurrentLanguage, out var dict) && dict.TryGetValue(key, out var value)) {
            return value;
        }

        if (_resources[UiLanguage.English].TryGetValue(key, out var fallback)) {
            return fallback;
        }

        return key;
    }
}
