using System.Windows;
using System.Windows.Media;
using Cbdb.App.Core;

namespace Cbdb.App.Desktop.Localization;

public sealed class AppLocalizationService : ILocalizationService {
    private readonly Dictionary<UiLanguage, Dictionary<string, string>> _resources = new() {
        [UiLanguage.English] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase) {
            ["window.title"] = "NAVIGATION_PANE",
            ["header.main"] = "China Biographical Database (CBDB)",
            ["button.browse"] = "Browse",
            ["button.check_db"] = "Check DB",
            ["button.users_guide"] = "Users Guide",
            ["button.exit"] = "Exit",
            ["button.report_error"] = "Report an Error",
            ["button.change_index_address"] = "Change Index Address Ranking",
            ["button.relink_tables"] = "Relink Tables / Change Dataset",
            ["module.browser"] = "Look Up Data on an Individual",
            ["module.entry"] = "Query by Methods of Entry into Government",
            ["module.office"] = "Query Office Holding",
            ["module.kinship"] = "Query Kinship",
            ["module.associations"] = "Query Associations",
            ["module.networks"] = "Query Social Networks",
            ["module.association_pairs"] = "Query Pair-wise Associations",
            ["module.place"] = "Query Place Associations",
            ["module.status"] = "Query Status",
            ["module.texts"] = "Query Texts",
            ["status.ready"] = "Ready",
            ["status.checking"] = "Checking...",
            ["status.connected"] = "Connected",
            ["status.failed"] = "Failed",
            ["status.language_set"] = "Language switched",
            ["status.module_selected"] = "Module selected: {0}",
            ["msg.module_todo"] = "{0} module is not implemented yet. Next step: wire this button to its page/query workflow.",
            ["msg.report_todo"] = "Error reporting flow not wired yet. We can route this to an issue form or local feedback dialog.",
            ["msg.index_addr_todo"] = "This will open Address Rank editor + Index Address rebuild page in the next implementation step.",
            ["msg.dataset_hint"] = "Use Browse to select another SQLite file, then click Check DB.",
            ["msg.user_guide_opened"] = "Users Guide opened",
            ["msg.user_guide_failed"] = "Users Guide failed",
            ["msg.user_guide_not_found"] = "Guide file not found: {0}",
            ["msg.sqlite_missing"] = "SQLite file does not exist. Please choose a valid CBDB SQLite file first.",
            ["msg.browser_opened"] = "Person Browser opened.",
            ["dialog.select_sqlite"] = "Select CBDB SQLite file",
            ["browser.window_title"] = "Person Browser",
            ["browser.search"] = "Search",
            ["browser.clear"] = "Clear",
            ["browser.save_to_file"] = "Save to File",
            ["browser.search_by_name_office"] = "Search by Surname + Office",
            ["browser.keyword_tooltip"] = "Search by name, Chinese name, pinyin, or alt names",
            ["browser.tab_basic"] = "Basic",
            ["browser.tab_counts"] = "Counts",
            ["browser.tab_related"] = "Related",
            ["browser.tab_birth_death"] = "Basic Information",
            ["browser.tab_addresses"] = "Addresses",
            ["browser.tab_alt_names"] = "Alt. Names",
            ["browser.tab_writings"] = "Writings",
            ["browser.tab_postings"] = "Postings",
            ["browser.tab_entry"] = "Entry",
            ["browser.tab_events"] = "Events",
            ["browser.tab_status"] = "Status",
            ["browser.tab_kinship"] = "Kinship",
            ["browser.tab_associations"] = "Associations",
            ["browser.tab_possessions"] = "Possessions",
            ["browser.tab_sources"] = "Sources",
            ["browser.tab_institutions"] = "Institutions",
            ["browser.grid_person_id"] = "ID",
            ["browser.grid_name"] = "Name",
            ["browser.grid_name_chn"] = "Chinese Name",
            ["browser.grid_name_rm"] = "Pinyin",
            ["browser.grid_index_year"] = "Index Year",
            ["browser.grid_index_address"] = "Index Address",
            ["browser.person_id"] = "Person ID",
            ["browser.name"] = "Name",
            ["browser.name_chn"] = "Chinese Name",
            ["browser.dynasty"] = "Dynasty",
            ["browser.index_year"] = "Index Year",
            ["browser.birth_death"] = "Birth / Death",
            ["browser.gender"] = "Gender",
            ["browser.index_address"] = "Index Address",
            ["browser.female"] = "Female",
            ["browser.notes"] = "Notes",
            ["browser.all_fields_header"] = "All BIOG_MAIN Fields",
            ["browser.count_altnames"] = "Alt Names",
            ["browser.count_kin"] = "Kinship",
            ["browser.count_assoc"] = "Associations",
            ["browser.count_office"] = "Offices",
            ["browser.count_entry"] = "Entries",
            ["browser.count_status"] = "Status",
            ["browser.count_texts"] = "Texts",
            ["browser.search_result_count"] = "Results: {0}",
            ["browser.search_result_count_more"] = "Loaded: {0} (scroll down to load more)",
            ["browser.loading_more"] = "Loading more...",
            ["browser.load_related"] = "Load",
            ["browser.related_primary"] = "Primary",
            ["browser.related_secondary"] = "Secondary",
            ["browser.related_note"] = "Note",
            ["browser.loading_related"] = "Loading details...",
            ["browser.related_result_count"] = "Details: {0}",
            ["browser.sqlite_missing"] = "SQLite file does not exist.",
            ["msg.query_shell_opened"] = "Query module shell opened.",
            ["qm.select_filter"] = "Select",
            ["qm.select_entry"] = "Select Entry",
            ["qm.select_association"] = "Select Association",
            ["qm.select_office"] = "Select Office",
            ["qm.select_person"] = "Select Person",
            ["qm.select_first_person"] = "Select First Person",
            ["qm.select_place"] = "Select Place",
            ["qm.select_status"] = "Select Status",
            ["qm.select_text_category"] = "Select Text Category",
            ["qm.import_list"] = "Import List",
            ["qm.import_people"] = "Import People",
            ["qm.import_places"] = "Import Places",
            ["qm.save_list"] = "Save List",
            ["qm.all_places"] = "All Places",
            ["qm.type"] = "Type",
            ["qm.index_years"] = "Index Years",
            ["qm.dynasties"] = "Dynasties",
            ["qm.date_mode"] = "Date Mode",
            ["qm.from"] = "From",
            ["qm.to"] = "To",
            ["qm.no_dates"] = "No Dates",
            ["qm.use_index_years"] = "Use Index Years",
            ["qm.use_dynasties"] = "Use Dynasties",
            ["qm.include_subunits"] = "Include Subordinate Units",
            ["qm.use_xy"] = "Use XY References",
            ["qm.display_language"] = "Display Language:",
            ["qm.include_kinship_relations"] = "Include Kinship Relations",
            ["qm.max_node_distance"] = "Max Node Dist.",
            ["qm.max_loop"] = "Max Loop #",
            ["qm.max_ancestor"] = "Max Ancestor Gen.",
            ["qm.tab_main"] = "Results",
            ["qm.tab_secondary"] = "Secondary",
            ["qm.tab_people"] = "People",
            ["qm.tab_aggregate"] = "Aggregate",
            ["qm.tab_entry"] = "Entry",
            ["qm.tab_associations"] = "Associations",
            ["qm.tab_office_postings"] = "Office Postings",
            ["qm.tab_people_office"] = "People in Office",
            ["qm.tab_kinship_network"] = "Kinship Network",
            ["qm.tab_ego_kinship"] = "Ego-Relative Kinship Network",
            ["qm.tab_relation_types"] = "Select Types of Relations",
            ["qm.tab_network_relations"] = "Social Network Relationship",
            ["qm.tab_people_network"] = "People in the Social Network",
            ["qm.tab_aggregate_relations"] = "Aggregated Social Relations",
            ["qm.tab_place_relations"] = "Places-People-Relations",
            ["qm.tab_aggregate_people_places"] = "Aggregated People and Places",
            ["qm.tab_status"] = "Status",
            ["qm.tab_texts_roles"] = "Texts and Roles",
            ["qm.run_query"] = "Run Query",
            ["qm.save_person_ids"] = "Store Person IDs",
            ["qm.save_gis"] = "Save to GIS",
            ["qm.encoding"] = "Encoding:",
            ["qm.help"] = "Help",
            ["qm.prototype_hint"] = "UI prototype based on Chapter 3 layout"
        },
        [UiLanguage.TraditionalChinese] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase) {
            ["window.title"] = "導航面板",
            ["header.main"] = "中國歷代人物傳記資料庫",
            ["button.browse"] = "選擇檔案",
            ["button.check_db"] = "檢查資料庫",
            ["button.users_guide"] = "用戶指南",
            ["button.exit"] = "退出",
            ["button.report_error"] = "問題回報",
            ["button.change_index_address"] = "修改索引地址排序",
            ["button.relink_tables"] = "切換資料集",
            ["module.browser"] = "按人查詢",
            ["module.entry"] = "按入仕途徑查詢",
            ["module.office"] = "官職查詢",
            ["module.kinship"] = "親屬關係查詢",
            ["module.associations"] = "社會關係查詢",
            ["module.networks"] = "社會網絡查詢",
            ["module.association_pairs"] = "兩人關係網交集查詢",
            ["module.place"] = "地區關係查詢",
            ["module.status"] = "社會區分查詢",
            ["module.texts"] = "文本關係查詢",
            ["status.ready"] = "就緒",
            ["status.checking"] = "檢查中...",
            ["status.connected"] = "連線成功",
            ["status.failed"] = "連線失敗",
            ["status.language_set"] = "語言已切換",
            ["status.module_selected"] = "已選模組：{0}",
            ["msg.module_todo"] = "模組「{0}」尚未實作。下一步將接入對應查詢頁面。",
            ["msg.report_todo"] = "問題回報流程尚未接線，後續可接入線上表單或本地回饋視窗。",
            ["msg.index_addr_todo"] = "下一步會在此接入 Address Rank 編輯與 Index Address 重建功能。",
            ["msg.dataset_hint"] = "請先選擇 SQLite 檔案，再按「檢查資料庫」。",
            ["msg.user_guide_opened"] = "已開啟用戶指南",
            ["msg.user_guide_failed"] = "開啟用戶指南失敗",
            ["msg.user_guide_not_found"] = "找不到指南檔案：{0}",
            ["msg.sqlite_missing"] = "SQLite 檔案不存在，請先選擇有效的 CBDB SQLite 檔案。",
            ["msg.browser_opened"] = "已開啟人物瀏覽。",
            ["dialog.select_sqlite"] = "選擇 CBDB SQLite 檔案",
            ["browser.window_title"] = "人物瀏覽",
            ["browser.search"] = "查詢",
            ["browser.clear"] = "清除",
            ["browser.save_to_file"] = "存成檔案",
            ["browser.search_by_name_office"] = "依姓名、拼音或別名查詢",
            ["browser.keyword_tooltip"] = "可用姓名、中文名、拼音或別名查詢",
            ["browser.tab_basic"] = "基本",
            ["browser.tab_counts"] = "統計",
            ["browser.tab_birth_death"] = "基本資料",
            ["browser.tab_addresses"] = "地址",
            ["browser.tab_alt_names"] = "別名",
            ["browser.tab_writings"] = "著作",
            ["browser.tab_postings"] = "任官",
            ["browser.tab_entry"] = "入仕",
            ["browser.tab_events"] = "事件",
            ["browser.tab_status"] = "身份",
            ["browser.tab_kinship"] = "親屬",
            ["browser.tab_associations"] = "社會關係",
            ["browser.tab_possessions"] = "財產",
            ["browser.tab_sources"] = "來源",
            ["browser.tab_institutions"] = "機構",
            ["browser.grid_person_id"] = "人物 ID",
            ["browser.grid_name"] = "姓名",
            ["browser.grid_name_chn"] = "中文姓名",
            ["browser.grid_name_rm"] = "拼音",
            ["browser.grid_index_year"] = "索引年",
            ["browser.grid_index_address"] = "索引地址",
            ["browser.person_id"] = "人物 ID",
            ["browser.name"] = "姓名",
            ["browser.name_chn"] = "中文名",
            ["browser.dynasty"] = "朝代",
            ["browser.index_year"] = "索引年",
            ["browser.birth_death"] = "生 / 卒",
            ["browser.gender"] = "性別",
            ["browser.index_address"] = "索引地址",
            ["browser.female"] = "女性",
            ["browser.notes"] = "備註",
            ["browser.all_fields_header"] = "BIOG_MAIN 全部欄位",
            ["browser.count_altnames"] = "別名",
            ["browser.count_kin"] = "親屬",
            ["browser.count_assoc"] = "關係",
            ["browser.count_office"] = "任官",
            ["browser.count_entry"] = "入仕",
            ["browser.count_status"] = "身份",
            ["browser.count_texts"] = "文本",
            ["browser.search_result_count"] = "結果數：{0}",
            ["browser.search_result_count_more"] = "已載入：{0}（向下捲動可繼續載入）",
            ["browser.loading_more"] = "載入更多中...",
            ["browser.loading_related"] = "載入明細中...",
            ["browser.related_result_count"] = "明細筆數：{0}",
            ["browser.sqlite_missing"] = "SQLite 檔案不存在。"
        },
        [UiLanguage.SimplifiedChinese] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase) {
            ["window.title"] = "导航面板",
            ["header.main"] = "中国历代人物传记资料库",
            ["button.browse"] = "选择文件",
            ["button.check_db"] = "检查数据库",
            ["button.users_guide"] = "用户指南",
            ["button.exit"] = "退出",
            ["button.report_error"] = "问题回报",
            ["button.change_index_address"] = "修改索引地址排序",
            ["button.relink_tables"] = "切换数据集",
            ["module.browser"] = "按人查询",
            ["module.entry"] = "按入仕途径查询",
            ["module.office"] = "官职查询",
            ["module.kinship"] = "亲属关系查询",
            ["module.associations"] = "社会关系查询",
            ["module.networks"] = "社会网络查询",
            ["module.association_pairs"] = "两人关系网交集查询",
            ["module.place"] = "地区关系查询",
            ["module.status"] = "社会区分查询",
            ["module.texts"] = "文本关系查询",
            ["status.ready"] = "就绪",
            ["status.checking"] = "检查中...",
            ["status.connected"] = "连接成功",
            ["status.failed"] = "连接失败",
            ["status.language_set"] = "语言已切换",
            ["status.module_selected"] = "已选模块：{0}",
            ["msg.module_todo"] = "模块“{0}”尚未实现。下一步将接入对应查询页面。",
            ["msg.report_todo"] = "问题回报流程尚未接线，后续可接入线上表单或本地反馈窗口。",
            ["msg.index_addr_todo"] = "下一步会在此接入 Address Rank 编辑与 Index Address 重建功能。",
            ["msg.dataset_hint"] = "请先选择 SQLite 文件，再点“检查数据库”。",
            ["msg.user_guide_opened"] = "已打开用户指南",
            ["msg.user_guide_failed"] = "打开用户指南失败",
            ["msg.user_guide_not_found"] = "找不到指南文件：{0}",
            ["msg.sqlite_missing"] = "SQLite 文件不存在，请先选择有效的 CBDB SQLite 文件。",
            ["msg.browser_opened"] = "已打开人物浏览。",
            ["dialog.select_sqlite"] = "选择 CBDB SQLite 文件",
            ["browser.window_title"] = "人物浏览",
            ["browser.search"] = "查询",
            ["browser.clear"] = "清除",
            ["browser.save_to_file"] = "存成檔案",
            ["browser.search_by_name_office"] = "依姓名、拼音或別名查詢",
            ["browser.keyword_tooltip"] = "可用姓名、中文名、拼音或别名查询",
            ["browser.tab_basic"] = "基本",
            ["browser.tab_counts"] = "统计",
            ["browser.grid_person_id"] = "ID",
            ["browser.grid_name"] = "姓名",
            ["browser.grid_name_chn"] = "中文姓名",
            ["browser.grid_name_rm"] = "拼音",
            ["browser.grid_index_year"] = "索引年",
            ["browser.grid_index_address"] = "索引地址",
            ["browser.person_id"] = "人物 ID",
            ["browser.name"] = "姓名",
            ["browser.name_chn"] = "中文名",
            ["browser.dynasty"] = "朝代",
            ["browser.index_year"] = "索引年",
            ["browser.birth_death"] = "生 / 卒",
            ["browser.gender"] = "性别",
            ["browser.index_address"] = "索引地址",
            ["browser.female"] = "女性",
            ["browser.notes"] = "備註",
            ["browser.all_fields_header"] = "BIOG_MAIN 全部欄位",
            ["browser.count_altnames"] = "别名",
            ["browser.count_kin"] = "亲属",
            ["browser.count_assoc"] = "关系",
            ["browser.count_office"] = "任官",
            ["browser.count_entry"] = "入仕",
            ["browser.count_status"] = "身份",
            ["browser.count_texts"] = "文本",
            ["browser.search_result_count"] = "结果数：{0}",
            ["browser.search_result_count_more"] = "已加载：{0}（向下滚动可继续加载）",
            ["browser.loading_more"] = "加载更多中...",
            ["browser.loading_related"] = "加载明细中...",
            ["browser.related_result_count"] = "明细笔数：{0}",
            ["browser.sqlite_missing"] = "SQLite 文件不存在。"
        }
    };

    public UiLanguage CurrentLanguage { get; private set; } = UiLanguage.TraditionalChinese;

    public event EventHandler? LanguageChanged;

    public AppLocalizationService() {
        ApplyFontFamily(CurrentLanguage);
    }

    public void SetLanguage(UiLanguage language) {
        if (CurrentLanguage == language) {
            return;
        }

        CurrentLanguage = language;
        ApplyFontFamily(CurrentLanguage);
        LanguageChanged?.Invoke(this, EventArgs.Empty);
    }

    public string Get(string key) {
        if (_resources.TryGetValue(CurrentLanguage, out var dict) && dict.TryGetValue(key, out var value)) {
            return value;
        }

        if (_resources[UiLanguage.English].TryGetValue(key, out var fallback)) {
            return fallback;
        }

        return key;
    }

    private static void ApplyFontFamily(UiLanguage language) {
        if (Application.Current is null) {
            return;
        }

        var familyName = language switch {
            UiLanguage.SimplifiedChinese => "Microsoft YaHei UI",
            UiLanguage.TraditionalChinese => "Microsoft JhengHei UI",
            _ => "Segoe UI"
        };

        Application.Current.Resources["AppFontFamily"] = new FontFamily(familyName);
    }
}















